# name of workflow
name: deploy-blog

# what events we want to run this workflow
on:
  push:
    branches:
      - main
    # run this workflow, when there is changes in blog folder
    paths:
      - 'packages/blog-app/**'

defaults:
  run:
    working-directory: packages/blog-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      
      - name: Configure AWS Credentials
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Deploy to S3
      - uses: chrislennon/action-aws-cli@v1
        with:
          args: s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME}}/blog/latest

